### ISSUE TITLE
Provisioning of users in lookup server

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/globalsiteselector#2]
* setup lookup server
* enable this app in master mode on instance-A
* enable this app in slave mode on instance-B
* try to login via instance-A into instance-B
* actual: nothing happens
* expected: login to instance-B

What is the problem: Not a single user is listed in the lookup server.

@schiessle How did you tested this? This only works if every single user at least sets one attribute manually to "public" to get listed in the lookup server.

@oparoz FYI ;)

**Comment by MorrisJobke** [comment]
I found this: https://github.com/nextcloud/server/blob/7c2d473d7686f4824d3b7f05238d262e26d5efa2/apps/federatedfilesharing/lib/FederatedShareProvider.php#L991-L994

What does the admin need to do?

**Comment by MorrisJobke** [comment]
I would say, that the global scale setup means: I enable the globalsiteselector app and this app initially uploads the user IDs (and server URLs) in the specified lookup server. And it should also add/delete entries on update events of the user manager (user is added/removed). Additionally there should be a daily cron job that checks if this is in sync to avoid that the lookup server sync code missed and event and a user is not added to the lookup server.


> What is the problem: Not a single user is listed in the lookup server.

This is only the case if the user haven't any public info selected in the personal settings (which is the default).

**Comment by MorrisJobke** [comment]
@schiessle @oparoz Ping. This is quite urgent

**Comment by oparoz** [comment]
Ping @schiessle . Would be good to have an answer/fix this week.

**Comment by MorrisJobke** [comment]
Just discussed with @schiessle and @blizzz that the background job that fills the look up server once per day.

**Comment by oparoz** [comment]
OK, so the solution is to add an occ command or something similar?

**Comment by MorrisJobke** [comment]
> OK, so the solution is to add an occ command or something similar?

Or just a normal background job as we have it today (ref cron.php) ;)

**Comment by schiessle** [comment]
@MorrisJobke as you mentioned here https://github.com/nextcloud/globalsiteselector/issues/2#issuecomment-324287019 there should be already a cron job which runs once a day. So is this still a issue?

**Comment by MorrisJobke** [comment]
> @MorrisJobke as you mentioned here [#2 (comment)](https://github.com/nextcloud/globalsiteselector/issues/2#issuecomment-324287019) there should be already a cron job which runs once a day. So is this still a issue?

Haven't tested again. Also not on the list for a while, because of other issues. Maybe make a test setup and check. If it works for you, you could close this one.

**Comment by gaalos** [comment]
Hello @MorrisJobke  i'm sorry to ask a question there, but how can you setup lookup server on nextcloud. i did not foud any doc 
I supose your talking about that : 
https://github.com/nextcloud/lookup-server
Can you help me there ? 
Best regards

**Comment by MorrisJobke** [comment]
> nextcloud. i did not foud any doc
> I supose your talking about that :
> https://github.com/nextcloud/lookup-server
> Can you help me there ?

Documentation is here: https://github.com/nextcloud/lookup-server/blob/master/doc/installation.md

**Comment by gaalos** [comment]
@MorrisJobke 
 thx for your fast reply.
I don't understand if i need to install the lookup server inside a Nextcloud server or not ?

If not ? How can i configure lookup-server inside Nextcloud

**Comment by MorrisJobke** [comment]
> I don't understand if i need to install the lookup server inside a Nextcloud server or not ?
> 
> If not ? How can i configure nextcloud to use lookup-server

You don't need to set it up and you don't need to configure it. It is automatically configured correctly. And respects the settings of your user data. So you actively need to change them to be public in your user settings page.

**Comment by tanguy-opendsi** [comment]
Hi everyone.
I use external lookup-server too but nothing happen when i had it inside my nextcloud config : 


Master :

'gss.jwt.key' => 'XXX',

// operation mode
'gss.mode' => 'master',

// define a master admins, this users will not be redirected to a slave but are
// allowed to login at the master node to perform administration tasks
'gss.master.admin' => ['XXX'],

// define a class which will be used to decide on which server a user should be
// provisioned in case the lookup server doesn't know the user yet.
// Note: That this will create a user account on a global scale note for every user
//       so make sure that the Global Site Selector has verified if it is a valid user before.
//       The user disovery module might require additional config paramters you can find in
//       the documentation of the module
'gss.user.discovery.module' => '\OCA\GlobalSiteSelector\UserDiscoveryModules\UserDiscoverySAML',
'gss.discovery.saml.slave.mapping' => 'idp-parameter',

'loodkup_server' => 'http://54.38.253.0'



Slave :
.
'gss.jwt.key' => 'XXX',

// operation mode
'gss.mode' => 'slave',

// url of the master, so we can redirect the user back in case of an error
'gss.master.url' => 'http://XXX,
'loodkup_server' => 'http://54.38.253.0'

);


This is a demo and you can test the lookup-server  response if you want
On my access.log inside apache2 for lookup-server i did not found any request coming from the nextcloud's

I just have this log on the master server : 
{"reqId":"EvajXydarEXxQfuB8IFJ","level":3,"time":"2019-01-10T08:53:38+00:00","remoteAddr":"137.74.29.219","user":"--","app":"no app in context","method":"POST","url":"\/index.php\/login","message":{"Exception":"OC\\HintException","Message":"Could not find location for user, populate","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/hook.php","line":106,"function":"handleLoginRequest","class":"OCA\\GlobalSiteSelector\\Master","type":"->","args":[{"run":"*** sensitive parameter replaced ***","uid":"*** sensitive parameter replaced ***","password":"*** sensitive parameter replaced ***"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Server.php","line":406,"function":"emit","class":"OC_Hook","type":"::","args":["OC_User","pre_login",{"run":"*** sensitive parameter replaced ***","uid":"*** sensitive parameter replaced ***","password":"*** sensitive parameter replaced ***"}]},{"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Hooks\/EmitterTrait.php","line":99,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Hooks\/PublicEmitter.php","line":36,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->","args":["\\OC\\User","preLogin",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nextcloud\/core\/Controller\/LoginController.php","line":281,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->","args":["\\OC\\User","preLogin",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"tryLogin","class":"OC\\Core\\Controller\\LoginController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"core.login.tryLogin"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"core.login.tryLogin"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/login"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/globalsiteselector\/lib\/Master.php","Line":160,"Hint":"Could not find location for user, populate","CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"14.0.4.2"}


My first question is . I use http and ip (no domain name) 
did i have to use SSL and domain name ?

**Comment by MorrisJobke** [comment]
@tanguy-opendsi As this seems to be a setup issue and not a bug I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
