### ISSUE TITLE
Regex manual mapping not working. 

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/globalsiteselector#32]
Here you have our gss config :  

```
'gss.user.discovery.module’ => ’\\OCA\\GlobalSiteSelector\\UserDiscoveryModules\\ManualUserMapping',
  'gss.discovery.manual.mapping.regex' => true,
  'gss.discovery.manual.mapping.file' => '/var/www/nextcloud/config/gss-mapping.json',
  'gss.discovery.manual.mapping.parameter' => 'Auth-Service',
  'gs.enabled' => true,
  'gss.jwt.key' =>'12345',
  'gss.mode' => 'master',
  'gss.master.admin' => ['XXXX'],
  'lookup_server' => 'http://10.228.128.150/',
  'overwriteprotocol' => 'https',
  'debug' => true,
  "loglevel" => "0",

```

Here the mapping file :  

```
{
 "/\\\/DNUM\\\/SDCAST\\\/BST)*$/" : "https://gssb.XX.XX",
 "/\\\/DNUM\\\/SDCAST\\\/.*)*$/" : "https://gssc.XX.XX",
 "/\\S+/"  : "https://gssc.XX.XX",
 "/.*"  : "https://gssc.XX.XX",

}


```

Error : 

`

{"reqId":"nigRuGlfokDIkfRNNovh","level":3,"time":"2020-03-11T15:26:24+00:00","remoteAddr":"10.228.141.115","user":"--","app":"no app in context","method":"GET","url":"/index.php/apps/theming/js/theming?v=0","message":{"Exception":"OC\\HintException","Message":"Could not find location for user, 1477787","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/hook.php","line":111,"function":"handleLoginRequest","class":"OCA\\GlobalSiteSelector\\Master","type":"->","args":[{"run":true,"uid":"1477787","backend":"*** sensitive parameter replaced ***"}]},{"file":"/var/www/nextcloud/lib/private/legacy/user.php","line":168,"function":"emit","class":"OC_Hook","type":"::","args":["OC_User","pre_login",{"run":true,"uid":"1477787","backend":"*** sensitive parameter replaced ***"}]},{"file":"/var/www/nextcloud/lib/private/legacy/user.php","line":217,"function":"loginWithApache","class":"OC_User","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/base.php","line":1049,"function":"handleApacheAuth","class":"OC_User","type":"::","args":[]},{"file":"/var/www/nextcloud/lib/base.php","line":997,"function":"handleLogin","class":"OC","type":"::","args":[{"__class__":"OC\\AppFramework\\Http\\Request"}]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/globalsiteselector/lib/Master.php","Line":178,"Hint":"Could not find location for user, 1477787","CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0","version":"18.0.1.3"}`

Our lookup server config : 
=

```

$CONFIG = [
        //DB
        'DB' => [
                'host' => 'localhost',
                'db' => 'lookup',
                'user' => 'lookup',
                'pass' => 'lookup',
        ],

        // error verbose
        'ERROR_VERBOSE' => true,

        // logfile
        'LOG' => '/tmp/lookup.log',

        // replication logfile
        'REPLICATION_LOG' => '/tmp/lookup_replication.log',

        // max user search page. limit the maximum number of pages to avoid scraping.
        'MAX_SEARCH_PAGE' => 10,

        // max requests per IP and 10min.
        'MAX_REQUESTS' => 10000,

        // credential to read the replication log. IMPORTANT!! SET TO SOMETHING SECURE!!
        'REPLICATION_AUTH' => '',

        // credential to read the slave replication log. Replication slaves are read only and don't get the authkey. IMPORTANT!! SET TO SOMETHING SECURE!!
        'SLAVEREPLICATION_AUTH' => '',

        // the list of remote replication servers that should be queried in the cronjob
        'REPLICATION_HOSTS' => [
        ],

        // ip black list. usefull to block spammers.
        'IP_BLACKLIST' => [
        ],

        // spam black list. usefull to block spammers.
        'SPAM_BLACKLIST' => [
        ],

        // Email sender address
        'EMAIL_SENDER' => 'XXX',

        // Public Server Url
        'PUBLIC_URL' => 'http://10.228.128.150/',

        // does the lookup server run in a global scale setup
        'GLOBAL_SCALE' => true,

        // auth token
        'AUTH_KEY' => '12345',

    // twitter oauth credentials, needed to perform twitter verification
        'TWITTER' => [
                'CONSUMER_KEY' => '',
                'CONSUMER_SECRET' => '',
                'ACCESS_TOKEN' => '',
                'ACCESS_TOKEN_SECRET' => '',
        ]
];

```

Can you help us ?

**Comment by rullzer** [comment]
Solved in support
