### ISSUE TITLE
Nextcloud 20 compatibility

### ISSUE THREAD

**Issue by sunjam** [nextcloud/globalsiteselector#33]
Please update for compatibility with version 20.  Thanks!

**Comment by MorrisJobke** [comment]
cc @rullzer @schiessle

**Comment by useventsllc** [comment]
+1

**Comment by faust64** [comment]
Note there's a 1.4.0 that does seem to support nextcloud 20 & 21 - though unsure it takes the remark from #34 under consideration.
https://github.com/nextcloud/globalsiteselector/archive/v1.4.0.tar.gz

Not showing as the last release, nor in NextCloud Apps.
Would give it a try soon ...

**Comment by faust64** [comment]
sounds like it kinda works ... up to a point the CSP served with the login page prevents my browser from sending data to the slave server that should host my user.
Not sure that's completely related to NC 20+. Adding `set Headers` to my virtualhost was no use so far, ... not done yet ...

Using an LDAP authenticating users, I'm also unsure the manual user backend discovery ever worked.
The following should fix: https://github.com/nextcloud/globalsiteselector/pull/35

**Comment by faust64** [comment]
Something else I did not notice until today: checking the 0.4.0 code using the occ cli:

```
I have no name!@nextcloud-sub2-7f6c5f79f7-vm5fv:/var/www/html$ php occ app:check-code globalsiteselector
[30-Jan-2021 10:51:06 UTC] [owncloud][files_sharing][0] /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.
[30-Jan-2021 10:51:06 UTC] [owncloud][globalsiteselector][0] /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.
Analysing /var/www/html/custom_apps/globalsiteselector/lib/UserBackend.php
 2 errors
    line  126: OC_Util - Static method of private class must not be called
    line  409: OC_Hook - Static method of private class must not be called
Analysing /var/www/html/custom_apps/globalsiteselector/lib/AppInfo/Application.php
 1 errors
    line  114: OC_User - Static method of private class must not be called
App is not compliant
```

I don't have those errors checking other apps. There might still be stuff to fix over here ...

**Comment by salagula** [comment]
any update here? Would be great to have it working in v20 / v21

**Comment by salagula** [comment]
Looks like the GSS app will be only delivered to enterprise customers since some months. That’s why the v21/22 compatibility is most likely no longer given for „simple open source users“

**Comment by sunjam** [comment]
Seems it will be released eventually.

https://github.com/nextcloud/globalsiteselector/pull/42

**Comment by juliushaertl** [comment]
I just moved the CSP issue to a separate ticket to discuss possible solutions at https://github.com/nextcloud/globalsiteselector/issues/45

**Comment by ciroiriarte** [comment]
Is the Global Site Selector still an option for mere mortals to scale?. Or should I just look back to the previous recipe of component desegregation and component clustering to scale?

**Comment by sunjam** [comment]
Could this issue be re-opened until a version supporting 20+ is released to the appstore.
