### ISSUE TITLE
Failure in user creation in Lookup Server in a Nextcloud Enterprise 22 instance

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/globalsiteselector#53]
I have a test Global Scale instance and I'm trying to setup a node with Nextcloud  22.2.3 Enterprise( `gs-node02`), to an already working Global Scale instance made of a:

- `lookup-server`: 0.3.2
- `gs-node01`: Node, Nextcloud 21.0.7 Enterprise
- `gs-selector`: Global Selector, Nextcloud 21.0.7 Enterprise

I enable the global-site-selector app in the new node:

`usrv@gs-node02:~$ sudo -u www-data php /var/www/nextcloud/occ app:enable globalsiteselector
globalsiteselector 2.0.0 enabled
`

Add the following parameters in `config.php` in `gs-node02`:

`
    'lookup_server' => 'https://gs-lookup.localenv.com/index.php',
  'gs.enabled' => true,
  'gss.jwt.key' => 'random-key',
  'gss.mode' => 'slave',
  'gss.master.url' => 'https://gs-selector.localenv.com'
`

Then connect to the web ui of `gs-node02` as an admin (by passing the selector) and create a user. The user is created in the instance but not in the Lookup Server. The log shows the following error:

`
{
  "reqId": "rtJqTKpM8cpPsSm3eIOy",
  "level": 3,
  "time": "2021-11-23T17:48:21+00:00",
  "remoteAddr": "10.23.46.1",
  "user": "admin",
  "app": "no app in context",
  "method": "POST",
  "url": "/ocs/v2.php/cloud/users",
  "message": "Call to protected method OC\\Accounts\\AccountManager::getUser() from context 'OCA\\GlobalSiteSelector\\Slave'",
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0",
  "version": "22.2.3.1",
  "exception": {
    "Exception": "Exception",
    "Message": "Call to protected method OC\\Accounts\\AccountManager::getUser() from context 'OCA\\GlobalSiteSelector\\Slave'",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 156,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/ocs/v1.php",
        "line": 62,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/ocs/v2.php",
        "line": 23,
        "args": [
          "/var/www/nextcloud/ocs/v1.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 158,
    "Previous": {
      "Exception": "Error",
      "Message": "Call to protected method OC\\Accounts\\AccountManager::getUser() from context 'OCA\\GlobalSiteSelector\\Slave'",
      "Code": 0,
      "Trace": [
        {
          "file": "/var/www/nextcloud/apps/globalsiteselector/lib/Slave.php",
          "line": 119,
          "function": "getAccountData",
          "class": "OCA\\GlobalSiteSelector\\Slave",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/legacy/OC_Hook.php",
          "line": 106,
          "function": "createUser",
          "class": "OCA\\GlobalSiteSelector\\Slave",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/Server.php",
          "line": 548,
          "function": "emit",
          "class": "OC_Hook",
          "type": "::"
        },
        {
          "function": "OC\\{closure}",
          "class": "OC\\Server",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/Hooks/EmitterTrait.php",
          "line": 106,
          "function": "call_user_func_array"
        },
        {
          "file": "/var/www/nextcloud/lib/private/Hooks/PublicEmitter.php",
          "line": 40,
          "function": "emit",
          "class": "OC\\Hooks\\BasicEmitter",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/User/Manager.php",
          "line": 459,
          "function": "emit",
          "class": "OC\\Hooks\\PublicEmitter",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/User/Manager.php",
          "line": 396,
          "function": "createUserFromBackend",
          "class": "OC\\User\\Manager",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/apps/provisioning_api/lib/Controller/UsersController.php",
          "line": 410,
          "function": "createUser",
          "class": "OC\\User\\Manager",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 217,
          "function": "addUser",
          "class": "OCA\\Provisioning_API\\Controller\\UsersController",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 126,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
          "line": 156,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/lib/private/Route/Router.php",
          "line": 302,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::"
        },
        {
          "file": "/var/www/nextcloud/ocs/v1.php",
          "line": 62,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->"
        },
        {
          "file": "/var/www/nextcloud/ocs/v2.php",
          "line": 23,
          "args": [
            "/var/www/nextcloud/ocs/v1.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/var/www/nextcloud/apps/globalsiteselector/lib/Slave.php",
      "Line": 213
    },
    "CustomMessage": "--"
  }
}
`

Besides the error, that should be solved, I think the user shouldn't be created locally if the user is not created in the Lookup Server for any reason. In other words the operation, local user creation + lookup server user creation, should be atomic.

**Comment by pmarini-nc** [comment]
It works fine with:

- Nextcloud 23.0.0
- globalsiteselector: 2.1.0
- lookup-server: 0.3.2

**Comment by PVince81** [comment]
@pmarini-nc did you get a chance to retest with NC 23 enterprise as discussed before ?

**Comment by PVince81** [comment]
closing as it was reported working with 23
