### ISSUE TITLE
Nextcloud 22: Global Site Selector cannot find the location of a valid user

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/globalsiteselector#54]
The Global Site Selector is not able to redirect the user to an existing valid Global Scale node when installed on a Nextcloud 22.2.3 Enterprise.

The error shown in the web login page is: Could not find location for user

The same Global Scale configuration (same nodes, same lookup server, same configuration values in selector machine) works fine if the Global Site Selector is installed on a Nextcloud 21.0.7 Enterprise.

**Comment by pmarini-nc** [comment]
It works with:

- Nextcloud 23.0.0
. globalsiteselector: 2.1.0

**Comment by PVince81** [comment]
closing then
