### ISSUE TITLE
Cross-node share fails if gs.federation is set to its default value

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/globalsiteselector#55]
In the following setup:

- Global Site Selector Node: Nextcloud Enterprise 21.0.7 with Global Site Selector 2.0.0
- Global Scale Nodes. Nextcloud Enterprise 21.0.7  with Global Site Selector 2.0.0

if a user user1@gs-node1 tries to share a resource with user user1@gs-node2 the share fails with  

```
Error creating the share: Sharing Templates failed, could not find user1@gs-node2, maybe the server is currently unreachable or uses a self-signed certificate.
```

gs-node2 is reachable from gs-node1 (they are on the same network) and no self-signed certificate are in use (I'm using mkcert to simulate trusted certificates).

If I set `gs.federation` to `true`, it works. According to [documentation](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html) though, I understand that setting this parameter to true shouldn't be needed in a Global Scale setting.

**Comment by juliushaertl** [comment]
This seems to be a server issue actually, see https://github.com/nextcloud/server/issues/14323 from the implementation I cannot really see yet how the gs nodes should be allowed if the mode is set to internal.

**Comment by pmarini-nc** [comment]
Thank you @juliushaertl . I'm not sure then if we should keep this issue open or not?

**Comment by juliushaertl** [comment]
Fine to close here I think, maybe you can just add the server related ticket to the overviews where this one was mentioned.

**Comment by pmarini-nc** [comment]
Sure
