### ISSUE TITLE
Make redirecting work as expected

### ISSUE THREAD

**Issue by szaimen** [nextcloud/globalsiteselector#62]
Follow-up to #61

I had a call with @schiessle and Pietro today and we discussed how redirecting should work:

Basically, if you open any url of your node and are not logged in, you should be redirected to the gss-selector, and after login redirected to the url that you wanted to the first place.

It could work like this:
1. Try to open any link of your node when you are not logged in
2. Get redirected to the gss-selector and put the relative url into the url as redirect_url param
3. log in on the gss-selector
4. redirect to the correct site on the node

**Comment by juliushaertl** [comment]
@szaimen Did you have a test setup for #61 ?

Looking at the request of a setup I just seen we should probably just redirect to /index.php/login?redirect_url instead of /?redirect_url.

**Comment by juliushaertl** [comment]
<img width="349" alt="Screenshot 2022-12-02 at 10 52 34" src="https://user-images.githubusercontent.com/3404133/205265806-f1a61d33-4ca1-48ea-a96b-8f057c32996c.png">

**Comment by juliushaertl** [comment]
Looking at the code something like this should work:

```
diff --git a/appinfo/app.php b/appinfo/app.php
index bea4bc2..945ec5c 100644
--- a/appinfo/app.php
+++ b/appinfo/app.php
@@ -45,7 +45,7 @@ if (!$userSession->isLoggedIn() && !empty($masterUrl) &&
        }

        if(isset($params['redirect_url'])) {
-               $masterUrl .= '?redirect_url=' . $params['redirect_url'];
+               $masterUrl = rtrim($masterUrl, '/') . '/index.php/login?redirect_url=' . $params['redirect_url'];
        }
```

**Comment by szaimen** [comment]
> @szaimen Did you have a test setup for #61 ?

No, unfortunately not but @pmarini-nc has and confirmed that it fixed the security bug👍

You could also ask him if he could test your patch...

**Comment by ArtificialOwl** [comment]
confirm as fixed
